Add repeat mode toggle
jorenvo/simple-mpc pull request #13
Opened 2022-02-09 19:56 UTC by josephmturner

This feature would be improved if the message read "Repeat mode on" or "Repeat mode off". I think we'd want to parse the output of the `mpc` command, which reveals the state of repeat mode.

I'm not sure the best way to do that (or even if you consider that to be within the scope of `simple-mpc`). Thank you!

2022-02-12 20:06 UTC, jorenvo requested changes
Thanks, there's a couple of small comments to resolve before this can be merged.

2022-02-12 20:06 UTC, jorenvo commented on simple-mpc.el
> +              "      * toggle [r] mode\n"
```suggestion
              "      * toggle [r]epeat mode\n"
```

I would also prefer this at the end of the `controls` section. By default it will repeat the current playlist but if `single` mode is enabled it will repeat the current song.

2022-02-12 20:06 UTC, jorenvo commented on simple-mpc-mode.el
> +    (define-key map "r" 'simple-mpc-toggle-repeat)
Let's move this under `simple-mpc-decrease-volume` so it stays in the same order as in my other comment.

2022-02-12 20:06 UTC, jorenvo commented on simple-mpc.el
> +  (message "%s" "Toggled random mode."))
```suggestion
  (message "%s" "Toggled repeat mode."))
```

2022-02-13 04:08 UTC, josephmturner commented
Thank you for catching those mistakes! All fixed now.

2022-02-13 16:43 UTC, jorenvo requested changes
I forgot two small things, sorry about that. First off, because this is a non-trivial commit you should add your copyright to the top of `simple-mpc.el` after Sean. Secondly please capitalize the first word in your commit message for consistency. That way I can merge it directly and the PR won't show as "Closed" but as "Merged".

2022-02-15 18:17 UTC, josephmturner commented
Ok, those two changes have been made. Thank you!

2022-02-16 01:02 UTC, jorenvo approved these changes

2022-02-16 01:02 UTC, merged

2022-02-16 01:02 UTC, jorenvo commented
Thank you for your work!